# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Tom Doidge
tagline:          Blacksmith & Software Engineer
url:              http://tomdoidge.com
baseurl:          /
author:
  name:           Tom Doidge
  url:            http://tomdoidge.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tombdoidge/tombdoidge.github.io

# Custom header pages
pages_list:       
  About Me: '/about'
